export const itemList = [
  {
    name: "Weapon",
    sprite: "./assets/images/GunQuest/gun2.png",
    subject: "projectile",
    type: "new",
    stat: null,
    maxStat: null,
    value: null,
    color: "rgb(4,4,4)",
    height: 15,
    width: 25,
  },
  {
    name: "Ammo",
    sprite: "./assets/images/GunQuest/ammo.png",
    sound: "./assets/audio/effects/reload.wav",
    soundVolume: 0.8,
    subject: "projectile",
    type: "replenish",
    stat: "remainingAmmo",
    maxStat: "maxAmmo",
    value: 50,
    color: "rgb(255,255,255)",
    height: 20,
    width: 20,
  },
  {
    name: "Rotten Cherries",
    sprite: "./assets/images/GunQuest/cherries.png",
    sound: "./assets/audio/effects/cherry.wav",
    soundVolume: 0.8,
    subject: "player",
    type: "replenish",
    stat: "health",
    maxStat: "maxHealth",
    value: 20,
    color: "rgb(0,255,0)",
    height: 20,
    width: 20,
  },
  {
    name: "Moldy Corn",
    sprite: "./assets/images/GunQuest/corn.png",
    sound: "./assets/audio/effects/crunch.wav",
    soundVolume: 0.8,
    subject: "player",
    type: "replenish",
    stat: "stamina",
    maxStat: "maxStamina",
    value: 20,
    color: "rgb(255, 176,0)",
    height: 30,
    width: 12,
  },
  {
    name: "Points",
    sprite: "./assets/images/GunQuest/points.png",
    sound: "./assets/audio/effects/coin.wav",
    soundVolume: 0.8,
    subject: "player",
    type: "collectible",
    stat: "score",
    maxStat: null,
    value: 100,
    color: "rgb(4,4,4)",
    height: 20,
    width: 20,
  },
  {
    name: "Lantern",
    sprite: "./assets/images/GunQuest/lantern.png",
    sound: "./assets/audio/effects/lit.wav",
    soundVolume: 0.8,
    subject: "player",
    type: "global",
    stat: "score",
    maxStat: null,
    value: 100,
    color: "rgb(4,4,4)",
    height: 20,
    width: 20,
  },
];
