export const projectiles = [
  {
    id: 1,
    price: 100,
    type: "ranged",
    name: "Pistol",
    upgrades: {
      knockbackForce: 1,
      damage: 1,
      maxAmmo: 1,
      emitCooldown: 1,
    },
    speed: 250,
    lifespan: 110,
    damage: 9,
    color: "rgb(245, 222, 15)",
    glowColor: "rgb(255,234,0)",
    size: 4,
    emitCooldown: 320,
    remainingAmmo: 128,
    defaultMaxAmmo: 320,
    maxAmmo: 320,
    defaultKnockbackForce: 80,
    knockbackForce: 80,
    visibility: 2.4,
    image: "./assets/images/GunQuest/pistol.png",
    sound: "./assets/audio/effects/gunshot1.wav",
  },
  {
    id: 2,
    price: 250,
    type: "ranged",
    name: "Shotgun",
    upgrades: {
      knockbackForce: 1,
      damage: 1,
      maxAmmo: 1,
      emitCooldown: 1,
    },
    speed: 190,
    lifespan: 90,
    damage: 18,
    color: "rgb(120, 255, 15)",
    glowColor: "rgb(0,255,0)",
    size: 14,
    emitCooldown: 520,
    remainingAmmo: 96,
    defaultMaxAmmo: 240,
    maxAmmo: 240,
    defaultKnockbackForce: 420,
    knockbackForce: 420,
    visibility: 1.8,
    image: "./assets/images/GunQuest/shotgun.png",
    sound: "./assets/audio/effects/gunshot1.wav",
  },
  {
    id: 3,
    price: 800,
    type: "ranged",
    name: "Rifle",
    upgrades: {
      knockbackForce: 1,
      damage: 1,
      maxAmmo: 1,
      emitCooldown: 1,
    },
    speed: 450,
    lifespan: 300,
    damage: 32,
    color: "rgb(227, 131, 14)",
    glowColor: "rgb(255,136,0)",
    size: 6,
    emitCooldown: 820,
    remainingAmmo: 72,
    defaultMaxAmmo: 180,
    maxAmmo: 180,
    defaultKnockbackForce: 300,
    knockbackForce: 300,
    visibility: 1.4,
    image: "./assets/images/GunQuest/rifle.png",
    sound: "./assets/audio/effects/gunshot1.wav",
  },
  {
    id: 4,
    price: 1400,
    type: "ranged",
    name: "Sub Machine Gun",
    upgrades: {
      knockbackForce: 1,
      damage: 1,
      maxAmmo: 1,
      emitCooldown: 1,
    },
    speed: 220,
    lifespan: 100,
    damage: 12,
    color: "rgb(255, 220, 220)",
    glowColor: "rgb(255,0,123)",
    size: 4,
    emitCooldown: 100,
    remainingAmmo: 168,
    defaultMaxAmmo: 420,
    maxAmmo: 420,
    defaultKnockbackForce: 40,
    knockbackForce: 40,
    visibility: 2.2,
    image: "./assets/images/GunQuest/subby.png",
    sound: "./assets/audio/effects/gunshot1.wav",
  },
  {
    id: 5,
    price: 3800,
    type: "ranged",
    name: "Assault Rifle",
    upgrades: {
      knockbackForce: 1,
      damage: 1,
      maxAmmo: 1,
      emitCooldown: 1,
    },
    speed: 420,
    lifespan: 120,
    damage: 19,
    color: "rgb(255, 120, 120)",
    glowColor: "rgb(255,0,0)",
    size: 5,
    emitCooldown: 110,
    remainingAmmo: 288,
    defaultMaxAmmo: 720,
    maxAmmo: 720,
    defaultKnockbackForce: 120,
    knockbackForce: 120,
    visibility: 1.6,
    image: "./assets/images/GunQuest/assault.png",
    sound: "./assets/audio/effects/gunshot1.wav",
  },
  {
    id: 6,
    price: 8200,
    type: "ranged",
    name: "Light Machine Gun",
    upgrades: {
      knockbackForce: 1,
      damage: 1,
      maxAmmo: 1,
      emitCooldown: 1,
    },
    speed: 380,
    lifespan: 170,
    damage: 24,
    color: "rgb(255, 40, 40)",
    glowColor: "rgb(255,0,0)",
    size: 6,
    emitCooldown: 140,
    remainingAmmo: 480,
    defaultMaxAmmo: 1200,
    maxAmmo: 1200,
    defaultKnockbackForce: 240,
    knockbackForce: 240,
    visibility: 1.2,
    image: "./assets/images/GunQuest/lmg.png",
    sound: "./assets/audio/effects/gunshot1.wav",
  },
  {
    id: 7,
    price: 14000,
    type: "ranged",
    name: "Sling Shot",
    upgrades: {
      knockbackForce: 1,
      damage: 1,
      maxAmmo: 1,
      emitCooldown: 1,
    },
    speed: 100,
    lifespan: 120,
    damage: 50,
    color: "rgb(10, 10, 10)",
    glowColor: "rgb(255,0,0)",
    size: 13,
    emitCooldown: 500,
    remainingAmmo: 40,
    defaultMaxAmmo: 160,
    maxAmmo: 160,
    defaultKnockbackForce: 800,
    knockbackForce: 800,
    visibility: 0,
    image: "./assets/images/GunQuest/slingshot.png",
    sound: "./assets/audio/effects/gunshot1.wav",
  },
];
