export const upgrades = [
  {
    name: "Ammo",
    type: "percentage",
    projectileKey: "maxAmmo",
    defaultKey: "defaultMaxAmmo",
    projectileValue: 0.1,
    cost: 500,
    costMultiplier: 3,
    image: "./assets/images/GunQuest/ammoUp.png",
  },
  {
    name: "Damage",
    type: "increment",
    projectileKey: "damage",
    projectileValue: 2,
    cost: 300,
    costMultiplier: 3,
    image: "./assets/images/GunQuest/damageUp.png",
  },
  {
    name: "Speed",
    type: "increment",
    projectileKey: "emitCooldown",
    projectileValue: -5,
    cost: 400,
    costMultiplier: 3,
    image: "./assets/images/GunQuest/speedUp.png",
  },
  {
    name: "Knockback",
    type: "percentage",
    projectileKey: "knockbackForce",
    defaultKey: "defaultKnockbackForce",
    projectileValue: 0.2,
    cost: 200,
    costMultiplier: 3,
    image: "./assets/images/GunQuest/knockbackUp.png",
  },
];
